travis:
  secure:
    BINSTAR_TOKEN: A9x/8EbvPtRRgnCYQe0WNop5wtHy6Q+H5hNxIpOT8H70ZTkYgmHT1icYUDzkf24If87l/xND0W6RhAnxcEcvuxg7s6MU38HNNBEtiUDnK3fzMVH9qFfV36U7tQfOl8dD4N670ql0iklBxoxDYRxnbPdcEMp12w+ghmgw+7Z5zIJZEMTsnhOZGAvjiqf4AXoKEujn7+qsnMoYO/mcZyDwanzoTKjt6HGl0TPud3V3gaFJzuZlDfk95UPyWqvv6Vtuq0mWWu6xFusyCx2J7bWq8n9dKkLbprEO6FeB0RiYaS7+kGgS0zuoCATo4UFrr0lGPAULhN+JjXpUFT/zCKxRdwaAS2yKylpmF9eM+lUKktcjkmLlPmpi/ArMbWxn2y0rvU5fT5IICDWpYOXQRHDqpHI6MZARmOF+kpOGKjopzNSeQGT9pXTmZ8hQtmRADoosnT19XPLT+nIzK20JXcoofCCk4TmtfZkUhxKvxEtTUepE4pukzPVrP2eXRs13jdGPnNkvK7q02P6H6AZRnwNgwceto7OlUTF721d1lBLYPNAsIV9rgkMI22TN247iHcSvydIGaH5GXLvdZ0w94jHxPMdPyFWnl8yWm74Q2NAHn/Sc1G5kVsOd1CbnN9Qy5ra9nG4m3FuOSzkBhPFy0k20YOD0OLkTSlec9wFwIFi3aew=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
