travis:
  secure:
    BINSTAR_TOKEN: V4ouiossbbzuS5Gby0PSdDEPM64+tz6IoJB72ws9PA/s070+2DLXL67dNNtCG27fICvKh6XEF2P8Heir63mQ4A1iv/u7JAEWpr0gKk0pq4gKxhEO02ltQJ7D48Y57afyWKvQKfufA+y9WfiluLkYfIyk/GutrhrVEkgC4vPuC3gDR5nKbDqDyhMTordann8OYSA02mueO51eDhYgpZf64sq/Jm3qtE6wOp8f/Fo3KF8MqlMxCtGxlLU+GCPFXCgCbfjXVRNMrIazBeoNRE2YvxBnRhWHKDQDTTCz7CJxhncs/REdm2+X//EUnHpPu8cKkY1BPrEM0GzdiR25M+NFLSKcQtlPz+lzGRAJJwDVAuXLuimh7qWGNT/HN6WcuyX5cww8dnFIP+oRnD+Jgl5GdvO6a6+sOL9jrd9Fw44fukwNQ9fKsfa8jE2Y8RSKEdehkuZFJS6GjKu3bxn+KFyro81kf3xuOZ4361GSUVX8YWfUyJ90APjCERReAeGFHbAo9FVLOL9Wp4pxZQ7cysJ7c9JsuHM/lBH/RyvC7WdbJypswNsQGdyQ8bANbdoLhkXDgNvnHJvIvNE2QwdgvHW5++1zJ3c3rNq40aOCsx5u9pjfqPqdwoY0vsYc2Fqdx9QsDQIOu5B9/N3By9YxTI9VDwwOJ6WQLY6d30yGZdoaA/o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
