travis:
  secure:
    BINSTAR_TOKEN: DK3kyxQgLrBPbeIvb5JbweEYUlm5rJljN89kCtY4gTyXR8kWLpZeBrX6WnI13KNCvhCkQH4APXtbpTNmlA6Pc8BkVzU3CrV/r3ukNgND2GGMYplUPSv2A1ZLKViWs8OA/Wm0nzlgsdOmD+txdKnrZJDoPPZC1OMguzJQlWhTX/DpdWv/IGi1itZcIyg9ZT5pnMM8HbB31PYcAy081eJ1CsShaDdQY0M2DwZtVUf5w1teATd9go5xp6IsO8fWntopd8CWX4JQXip17FgI2sh/ZrkrIsBL1wjGXAw2+olu1oYlq/jEvWDfqJJp55z3e7me7MqawPlIOB5mUOFIdcZpsXrjUOGiJdS1dAlVAidwj4PssO3uP8rZXT++lRaiVKlbcyaXR5+CQhEzM/w8w5hbLXP73UbLNi/ewO6Uta3E0DJAGwr+T0ND/knxJ3wRk1A1HJQ6rblnCUO2euPKPsIat5A3n1P269s0EzYUvHDsrz1+eQh9auO1irvwuEULpE9tXHE+eucX2YcMFU+dyZ/p991Uk8GuF8YcDdXGlKfziNU03CIdOQA9wXIkJ5YGMq7UTEUSQyzCTHciIPaRHDM4PiD66nQ708OiiSicsVD1hmHqBl0DoB4HvShvKOWW6zax4aSJK1JLY+3H0r6H1BbBUWUwSckQbmlBxdlZEBfCBsg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
