travis:
  secure:
    BINSTAR_TOKEN: TF9DNuS37Yy1SilKa/pZlL3jGh06czI58Ph+HLmfYztd3AyXXhHK5UfceDOFc2dnZ9ilQNRpkjdzYjXNUn+eU8Mjpc6zRlZbAao5B9lylF+t9Fx8ruYJAP2H+afA+QMQmJjOYjTc7ec0dghHOFc3X+4edRb3cykgV58LbgYlqxv+UjWfYNHrPHNvBuXBaAtPHEk/jAEASXil5SEqwkPL11fFG1jVzrQRGs4ROFGjVosRTDoxmt6uOcfxQ+hDAXO0XLjN76kKU88QME8KjwBGGaqkt3qKOxrETUPVOND061CNsmHo4cR5eTZqEGAERTBF9K28wNK1Oep1nKfpFUuzDWe0Jqiqul48U+1YIEvm1VDPUHF/+vUJ7MHs2G0oCVHDrknC48n+peBfB+OGt5Ol4jcpJ+KOTTvisdgkNUcmmJ10C5JSeL4gDqwH7VHrRWNT43GUlHayD9o9vchBfEKwsiwsFg5ZWVlaeUW13w7cSR+LAbyqQlaNAalpCfXJ4V6EMSFTaQUCPvwnE3pyht3Sc9yUvTD8XbkxWZ4MePuISxVrtYIHHJnbrB6q3/TkvWSzf57LYiNdhnXy0VIzfTSXPjuT6xdqfvQaiWZNnJnXSySQfZJ3fvIxHAGb2b28N+sF7aa8ZrwIIAecQNnIgdsBVUnlpQZXlJvfHC2JXoGqVFs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
