travis:
  secure:
    BINSTAR_TOKEN: ZWVaxTOIxMUR3hzZIFnqZuk3TmziINekF838Ati1S3kFiGrZa1o+zuYXTE+tIdyCiMXj2SS9KKF19J1QRrwvFSuD4rrv8wMTPe/6shgNJh41dB4pQy1w+m/n6HErCASkFdsCPLG6Uo1Q68C2FdJ6B215tSxTxSb6+RlCc/Dhs7A760JtBl6zfUCNZFcI04EFe256Td7wvo4a2cRVAJ6XJbhrYjrFDEUUxdoIUaz0OwTdSIXrXoTrQ7AzyzMZ7zWlqsSVuIZ0EPU8jA71HxO8MYY0bt7EAU5EFVXvauj6ztFiUkTuCvU21baTQLHYRIIZM4CoSpP8Gd8xTfy6SOxdsfSFfINh8ost3akB84wfF1cxbGYReJqhKwoKUgVjxkJBhTzIgXRYB/YzpAYDn59HYlZh08aWgGJs0j4UElTyaslttqhaiP1GYwz14QrJzUvZwpYDg4wEloJDRIuKzTkmaVzSIqNHQAqv6FsbYK8/i1Sn8idcSq9jTDAjP4r7zHk5PqBfxCz8oWh9czdyoLS/4nQ1ThLifBprQt3bQpWH77EFCRYI4TO4HyJZORdeC67zsXjBjkWFiY9O6FgGV2V+SQqlfWI7XXxfPw1HOLfMoxXrd6hXAjUIFpMenagnjyjzR5SCD0k4Y7OXgWr5vkGJAtxBGdi2FPwu8nWCYnN1HVw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
