travis:
  secure:
    BINSTAR_TOKEN: JDaB8LHXQlWyi3CaQulNIt/EztE0zu8u2jCAlBKFrvUdAsF+mURdRjkXOc8OU7H9vudVJ9/Ri4FIb6crzyAj/t8RAQiiCqHd7UxzH1zc6MlEma2fUqjxyGcxjV/f6IjqfPdCNnSUprx+ZUHPDFZ9fyzZ74q+aYPS9oqb3czBjlsmXWxdFymuTB/+CmxzP1VHJ48Z7cQ0NC2XY9r8m8fHYJmQn4f4Y86FKbtji+BhUpkJuxugd9888eWr8oD+G370vtDMew7LFEQ2EB3YxAEaAT5ti3HHFgUBBmEKf0r3hjX2azC6HU9FQEM8UCGb7Eyuf8W5mvtAfIjTvZYEAf8KhhFuQJOmkSuutSiPx4MNd4JwhQjnCpvRqqWe4IFb8cYf23PqttHITV69Gjbp1mQFwBa+uTPyoDWXkjgtHEocolC43YeuTh9wKeBJg/aLWw/gXXakjDZ7b7RDZbUChbRUmb7YwGqvTJtKHyWKwmpOTeHHynKBQYyXliLIpZwg/nKH65HqOt5+uSiuRHIzHF6ptw3pX89aLFJolufe3AdpafHhA6uMsSmGxv9iLloxHdG9JDRlIMSKD3s+AyUbT8FksliPKxb0uIx5xQGgpY0S4tgw9eDCdElg5BigHgcVK579qKt8kdzS74V1hrnCbY7lhuvYYbHo120KrDNVdBP19ns=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
